jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS credentials for Docker
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Terraform Init (Docker)
      - name: Terraform Init
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/compiled/my_tf:/workspace \
            terraform-on-docker init

      # Terraform Apply (Docker)
      - name: Terraform Apply
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/compiled/my_tf:/workspace \
            terraform-on-docker apply -auto-approve
